baseURL = "https://0xffsec.com/handbook"
languageCode = "en-us"
title = "0xffsec Penetration Testing Handbook"
theme = "book"

googleAnalytics = "UA-142676329-2"
enableGitInfo = true
enableEmoji = true
enableRobotsTXT = true

[markup]
[markup.highlight]
    style = "native"
[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[params]
    BookRepo = "https://github.com/0xffsec/handbook"
    BookEditPath = 'edit/master/content'
    BookSection = '/'

[params.war]
    rhost = "10.0.0.3"
    rcidr = "10.0.0.0/24"
    rdomain = "example.com"
    ldomain = "example.evil"
    lhost = "10.0.0.1"
    lport = "1234"
    tfile = "filename.ext"
