baseURL = "https://0xffsec.com/notebook"
languageCode = "en-us"
title = "0xffsec Penetration Testing Notebook"
theme = "book"

googleAnalytics = "UA-142676329-2"
enableGitInfo = true

[markup]
[markup.highlight]
    style = "dracula"

[params]
    BookRepo = "https://github.com/0xffsec/notebook"
    BookEditPath = 'edit/master/content'
    BookSection = '/'

[params.war]
    rhost = "10.0.0.3"
    rcidr = "10.0.0.0/24"
    lhost = "10.0.0.1"
    lport = "1234"
