baseURL = "https://0xffsec.com/notebook"
languageCode = "en-us"
title = "Notebook"
theme = "book"

enableGitInfo = true

[markup]
[markup.highlight]
    style = "dracula"

[params]
    BookRepo = "https://github.com/0xffsec/notebook"
    BookEditPath = 'edit/master/content'
    BookSection = '/'
