baseURL = "https://0xffsec.com/notebook"
languageCode = "en-us"
title = "Notebook"
theme = "book"

enableGitInfo = true

[markup]
[markup.highlight]
    style = "dracula"

[params]
    rhost = "10.0.0.3"
    rcidr = "10.0.0.0/24"

    lhost = "127.0.0.1"
    lport = "1234"

    BookRepo = "https://github.com/0xffsec/notebook"
    BookEditPath = 'edit/master/content'
    BookSection = '/'
